#include "ts_gsolver.hh"

namespace tslam
{
    TSGSolver::TSGSolver() {};

    void TSGSolver::reconstruct(std::shared_ptr<tslam::TSTimber>& timber)
    {

        // TODO

        /* reconstruct algorithm
        ref1: polyFit (https://github.com/LiangliangNan/PolyFit)
        --- there is a licensed geometric solver Gurobi, this is not free and 
        we want to find another solution;


        Inspired byy polyfit
        00. group the tags first (?)
        0. create mesh planes scaled by 10e1000
        1. clip supporting planes with boundary box generated by all points (Open3d::bbox)

        2. refinement of planes selection
        3. intersection of planes
        4. selection of candidate rectangles (inbound points?)
        5. refinement and merging to create a manifolded, water-tight mesh

        */
    }
}