# to create from scratch: conda env create -f environment.yml
# to update the environment: conda env update --name myenv --file environment.yml --prune
# or update with environment activated: conda env update --file environment.yml --prune

name: tslameval
channels:
    - conda-forge
dependencies:
   - python==3.9
   - pip
   - av==10.0.0
   - pip:
     - NatNetClient==0.8.3
     - numpy==1.20.3
     - pyquaternion==0.9.9
     - opencv-python==4.7.0.72
     - tqdm==4.65.0
     - waiting==1.4.1
     - matplotlib==3.4.3
     - pandas==1.3.3
   - git