
# ----------------------------------------------------------------------------
# display status message for important variables
# ----------------------------------------------------------------------------
if(NOT TSLAM_QUIET)
  message(STATUS)
  message(STATUS "-------------------------------------------------------------------------------")
  message(STATUS "General configuration for ${PROJECT_NAME} ${PROJECT_VERSION}")
  message(STATUS "-------------------------------------------------------------------------------")
  message(STATUS)
  message(STATUS "    Built as dynamic libs?:" ${BUILD_SHARED_LIBS})
  message(STATUS "    Compiler:"                   "${CMAKE_COMPILER}"   "${CMAKE_CXX_COMPILER}")
  message(STATUS "    CMAKE_INSTALL_PREFIX:"       "${CMAKE_INSTALL_PREFIX}")


  message(STATUS "Build Type: ${CMAKE_BUILD_TYPE}")
  message(STATUS "C++ flags (Release):      ${CMAKE_CXX_FLAGS_RELEASE}")
  message(STATUS "C++ flags (Debug):        ${CMAKE_CXX_FLAGS_DEBUG}")
  message(STATUS "C++ flags (Relase+Debug): ${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
  message(STATUS "CMAKE_BINARY_DIR:         ${CMAKE_BINARY_DIR}")

  message(STATUS)
  message(STATUS "BUILD_4_API = ${BUILD_4_API}")
  message(STATUS "CMAKE_SYSTEM_PROCESSOR = ${CMAKE_SYSTEM_PROCESSOR}")
  message(STATUS "BUILD_SHARED_LIBS = ${BUILD_SHARED_LIBS}")
  message(STATUS "CMAKE_INSTALL_PREFIX = ${CMAKE_INSTALL_PREFIX}")
  message(STATUS "CMAKE_BUILD_TYPE = ${CMAKE_BUILD_TYPE}")
  message(STATUS "CMAKE_MODULE_PATH = ${CMAKE_MODULE_PATH}")
  message(STATUS "BUILD_UTILS = ${TSLAM_BUILD_UTILS}")
  message(STATUS "BUILD_TESTS = ${TSLAM_BUILD_TESTS}")
  message(STATUS "OPENCV_DIR = ${OpenCV_INCLUDE_DIRS}")
  message(STATUS "OPENCV_LIBS = ${OpenCV_LIBS}")
  message(STATUS "OPEMMP = ${OpenMP_FOUND}")
  message(STATUS "USE_OWN_CGAL = ${TSLAM_USE_OWN_CGAL}")
  message(STATUS "USE_OWN_EIGEN3 = ${TSLAM_USE_OWN_EIGEN3}")
  if(NOT TSLAM_USE_OWN_EIGEN3)
    message(STATUS "    EIGEN= ${EIGEN3_INCLUDE_DIR}")
  endif()
  # message( STATUS "BUILD_OWN_ARUCO= ${BUILD_OWN_ARUCO}")
  # message( STATUS "BUILD_OWN_FBOW= ${BUILD_OWN_FBOW}")
  # message( STATUS "BUILD_OWN_CVBA= ${BUILD_OWN_CVBA}")
  # message( STATUS "BUILD_OWN_XFLANN= ${BUILD_OWN_XFLANN}")
  # message( STATUS "BUILD_OWN_G2O= ${BUILD_OWN_G2O}")
  #message(STATUS "BUILD_GUI= ${TSLAM_BUILD_GUI}")
  message(STATUS "BUILD_DEBPACKAGE= ${TSLAM_BUILD_DEBPACKAGE}")

  message(STATUS "TSLAM_REQUIRED_LIBRARIES = PUBLIC: ${TSLAM_PUBLIC_EXTERNAL_LIBRARIES} PRIVATE: ${TSLAM_PRIVATE_EXTERNAL_LIBRARIES}")

  message(STATUS)
  message(STATUS "OpenCV_LIB_DIR=${OpenCV_LIB_DIR}")
  message(STATUS "CMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}")

  message(STATUS)
  message(STATUS)
  message(STATUS "Change a value with: cmake -D<Variable>=<Value>")
  message(STATUS)
endif()
